# GPT Model

In this notebook we will implement the GPT-2 model. 

To start, we implement at dummy class that shows the architecture of the neural network. 

Then, we implement the layers we mocked in the dummy GPT model.

Finally, we put everything back together with a few additions.

In [173]:
import torch
import torch.nn as nn

## Dummy GPT

We implement a dummy GPT class below, with the following architecture:


Architecture:
```
DummyGPT(
  (dropout): Dropout(p=0.1, inplace=False)
  (tokenEmbed): Embedding(50257, 768)
  (posEmbed): Embedding(1024, 768)
  (normLayer): DummyLayerNorm()
  (trfBlocks): Sequential(
    (0): DummyTransformer()
    (1): DummyTransformer()
    (2): DummyTransformer()
    (3): DummyTransformer()
    (4): DummyTransformer()
    (5): DummyTransformer()
    (6): DummyTransformer()
    (7): DummyTransformer()
    (8): DummyTransformer()
    (9): DummyTransformer()
    (10): DummyTransformer()
    (11): DummyTransformer()
  )
  (outLayer): Linear(in_features=768, out_features=50257, bias=False)
)
```

The model will be initialized using a configuration dictionary that will contain the number of layers and other model parameters. 

We use the parameters from GPT-2 for reference:

In [174]:
cfg = {
    "vocabSize": 50257, # Number of tokens in vocabulary.
    "contextLength": 1024, # Max. number of tokens the LLM sees per run.
    "embedDim": 768, # Size of the internal. embeddings used in the LLM attention mechanism.
    "nLayers" : 12, # Number of transformer layers.
    "dropRate": 0.1, # Feature dropout rate.
}


In [175]:
class DummyLayerNorm(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, x):
        return x

class DummyTransformer(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, x):
        return x

In [176]:
class DummyGPT(nn.Module):
    def __init__(self, cfg):
        super().__init__()
        # Dropout
        self.dropout = nn.Dropout(cfg["dropRate"])
        # Token embedding
        self.tokenEmbed = nn.Embedding(cfg["vocabSize"], cfg["embedDim"])
        # Positional embedding
        self.posEmbed = nn.Embedding(cfg["contextLength"], cfg["embedDim"])
        # Normalization
        self.normLayer = DummyLayerNorm()
        # Transformer Blocks
        self.trfBlocks = nn.Sequential(*[
            DummyTransformer() for _ in range(cfg["nLayers"])
        ])
        # Linear projection.
        self.outLayer = nn.Linear(cfg["embedDim"], cfg["vocabSize"], bias=False)

    def forward(self, x):
        b, seqLen = x.shape
        tokEmbeds = self.tokenEmbed(x)
        posEmbeds = self.posEmbed(torch.arange(seqLen, device=x.device))
        x = tokEmbeds + posEmbeds
        x = self.dropout(x)
        x = self.normLayer(x)
        for l in self.trfBlocks:
            x = l(x)
        return self.outLayer(x)

In [177]:
# Initialize model.
dummyGpt = DummyGPT(cfg)
dummyGpt

DummyGPT(
  (dropout): Dropout(p=0.1, inplace=False)
  (tokenEmbed): Embedding(50257, 768)
  (posEmbed): Embedding(1024, 768)
  (normLayer): DummyLayerNorm()
  (trfBlocks): Sequential(
    (0): DummyTransformer()
    (1): DummyTransformer()
    (2): DummyTransformer()
    (3): DummyTransformer()
    (4): DummyTransformer()
    (5): DummyTransformer()
    (6): DummyTransformer()
    (7): DummyTransformer()
    (8): DummyTransformer()
    (9): DummyTransformer()
    (10): DummyTransformer()
    (11): DummyTransformer()
  )
  (outLayer): Linear(in_features=768, out_features=50257, bias=False)
)

In [178]:
# Define a batch to be used for testing purposes
import tiktoken

tokenizer = tiktoken.get_encoding("gpt2")
batch = []
txt1 = "Every effort moves you"
txt2 = "Every day holds a"
batch.append(torch.tensor(tokenizer.encode(txt1)))
batch.append(torch.tensor(tokenizer.encode(txt2)))
batch = torch.stack(batch, dim=0)

In [180]:
# Initialize model and run model on batch.
# Model isn't trained and all ouputs are gibberish.
torch.manual_seed(123)

logits = dummyGpt(batch)  # shape: [batch, seqLen, vocabSize]
pred_ids = logits.argmax(dim=-1)  # shape: [batch, seqLen]
print(batch)
for i in range(pred_ids.shape[0]):
    print(tokenizer.decode(pred_ids[i].tolist()))


tensor([[6109, 3626, 6100,  345],
        [6109, 1110, 6622,  257]])
 bargainLogin UNIVERS Trident
 bargain Olsenconfidencemes


# Layer Normalization

Next step is to implement the layer normalization class.

Layer normalization is used to keep a stable model training, by reducing internal co-variate shift.  

Let's explain in more details:

- Covariate: Refers to the input features of a ML model.
- Shift : Distribution change.
- Internal : Refers to the internal covariates, which are the internal activations of the neural networks.


### Why does layer normalization help reduce internal covariate shift ?

While the model is trained, model weights are updated at each training step. Without normalization, each layer is forced to learn the new distribution of the previous layer outputs. Layer normalization helps by making the mean = 0 and variance = 1, maintaining the input feature distribution regardless of the iteration.

### How does it work ?

For an input vector `X = [x1, x2, ..., xn]`, layer normalization works by computing:

`z =  (  xi  - mean(X)  )  /  std(X) `

In practice, layer normalization includes two learnable terms that allow the model to rescale and shift the inputs, learning better representations of the input activations:

`z = γ * (  xi  - mean(X)  )  /  ( std(X) + ε )    +    β `

Where:
- `γ`: Scale
- `ε`: Small Epsilon, avoid division by 0.
- `β`: Shift

In [181]:
class LayerNorm(nn.Module):
    def __init__(self, embDim):
        super().__init__()
        # Scale parameter.
        self.scale = nn.Parameter(torch.ones(embDim))
        # Shift parameter.
        self.shift = nn.Parameter(torch.zeros(embDim))
        # Epsilon constant. Avoids division by zero.
        self.eps = 1e-8
    
    def forward(self, x):
        mean = x.mean(dim=-1, keepdim=True)
        var  = x.var(dim=-1, keepdim=True, unbiased=False) 
        normX = (x - mean) / torch.sqrt(var + self.eps)
        return self.scale * normX + self.shift

In [182]:
# Try LayerNorm.
torch.manual_seed(123)
torch.set_printoptions(sci_mode=False)

batch = torch.randn(2, 10)
print("Mean:\n ", batch.mean(dim=-1))
print("Variance :\n ", batch.var(dim=-1,  unbiased=False))

ln = LayerNorm(10)
out = ln(batch)
print("Norm. Mean:\n ", out.mean(dim=-1))
print("Norm. Variance :\n ", out.var(dim=-1,  unbiased=False))

Mean:
  tensor([ 0.2662, -0.7222])
Variance :
  tensor([0.5920, 1.1845])
Norm. Mean:
  tensor([0., 0.], grad_fn=<MeanBackward1>)
Norm. Variance :
  tensor([1.0000, 1.0000], grad_fn=<VarBackward0>)
